[package]
name = "atomic_http"
version = "0.1.7"
authors = ["hsng95@gmail.com"]
description = "High level HTTP server library"
homepage = "https://github.com/rabbitson87/atomic_http"
repository = "https://github.com/rabbitson87/atomic_http"
keywords = ["http", "server", "web"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.77"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.38.0", features = ["net", "macros", "io-util", "fs"] }
async-trait = "0.1.80"
http = "1.1.0"
serde_json = "1.0.117"
serde = "1.0.203"
